language: java
services:
- docker
script:
- |

  if [ "$TRAVIS_BRANCH" = "master" ]; then
    fbn_token_url="MASTER_FBN_TOKEN_URL"
    fbn_username="MASTER_FBN_USERNAME"
    fbn_password="MASTER_FBN_PASSWORD"
    fbn_clientid="MASTER_FBN_CLIENT_ID"
    fbn_client_secret="MASTER_FBN_CLIENT_SECRET"
    fbn_lusid_api_url="MASTER_FBN_LUSID_API_URL"    
  else
    fbn_token_url="DEVELOP_FBN_TOKEN_URL"
    fbn_username="DEVELOP_FBN_USERNAME"
    fbn_password="DEVELOP_FBN_PASSWORD"
    fbn_clientid="DEVELOP_FBN_CLIENT_ID"
    fbn_client_secret="DEVELOP_FBN_CLIENT_SECRET"
    fbn_lusid_api_url="DEVELOP_FBN_LUSID_API_URL"
  fi

  cd sdk
  docker build -t lusid-sdk-java-preview-test .
  docker run \
    -e FBN_TOKEN_URL=${!fbn_token_url} \
    -e FBN_USERNAME=${!fbn_username} \
    -e FBN_PASSWORD=${!fbn_password} \
    -e FBN_CLIENT_ID=${!fbn_clientid} \
    -e FBN_CLIENT_SECRET=${!fbn_client_secret} \
    -e FBN_LUSID_API_URL=${!fbn_lusid_api_url} \
    -v $(pwd):/usr/src/ \
    lusid-sdk-java-preview-test
  
notifications:
  slack:
    rooms:
      secure: "gB9lWzqg4mRpNbJdbQ5PXDCwKICYP4JGRI9t+6cuHlIZOIcaed+qb4wRW7U6RKUuT1nvXmLcvtW8Jz2jq7SJBPVcPGKf/z65G4dx6eQUX/YeuUmhBdZd4D0ksUnL2i5HsptoBSed6ZaF9qzwZ26Rhwf6b8DZyx0MS3ITLQbN3OFxP7TOsw6CITCtwHU3WLkbUx15H2uY1ZUNX+TSkt3hQr+k38BGV1VIO0dVuCF7OivXA6ITv71DytkGfI6bgM/R979Mzmfh0UBmtOiNqMd//6fXDPHLi5y6b+zhK2B+JgAX/oYmFr3zJXwJL/gemF9OwGOv0JujNRn0eIOulmB43TMUTY7Yfk3SudC3GP+pEzHbaWRp20VBlzXck2qd9Ta3lpnXkv4Yzx+ozM1Ovzl/KazHKfUlILhczWdbO/pGfo1M5MY1masgB9KrFdMRJwWWbyw0WORLxNkmjEmLL/XyOpw/1LUxFyqRrRlO7ei2WDAucJ8YN0pHqjSaelVFQnqleOdBpeUTn2IvTWLNa/NrL5iq3hMMUjpgwB8s9gAgBwweGjSxreLFwwh3D3CGsk19feyJ8DhsG97iMjglu/B/0NLvAiLfNITTIFNKWU+E+S4J+gNAnKknG6kFwiPmJ+tHqBRy67KMnNJL4MEBXNhrMfRtQJC4z3kUVcihal4yBJA="
    on_failure: always

